######################################################################################
# GEOCODERJ
# Capture geocode latitude and longitude from many neighbour in Rio de Janeiro, Brazil
# Autor: Flavio Brito
# Language: R
# Library: ggmap
######################################################################################


#load libary ggmap
library(ggmap)

#Local adresses
local <- c(
  "Praça Mauá",
  "Praça da República", 
  "Mem de Sá ",
  "Cidade Nova",
  "Santa Tereza",
  "Catete",
  "Botafogo",
  "Rocinha",
  "Copacabana",
  "Ipanema",
  "Leblon",
  "Gávea",
  "Barra da Tijuca",
  "São Cristóvão",
  "Praça da Bandeira",
  "Tijuca",
  "Grajaú",
  "Bonsucesso",
  "Penha",
  "Meier",
  "Piedade",
  "Engenho Novo",
  "Todos os Santos",
  "Vicente de Carvalho",
  "Campinho",
  "Madureira",
  "Marechal Hermes",
  "Ricardo Albuquerque",
  "Taquara",
  "Realengo ",
  "Bangu ",
  "Campo Grande",
  "Santa Cruz",
  "Ilha do Governador",
  "Braz de Pina",
  "Pavuna",
  "Honório Gurgel",
  "Tanque",
  "Recreio",
  "Pedra de Guaratiba ",
  "Inhaúma ",
  "Alemão",
  "Seropédica",
  "Itaguaí",
  "Paracambí",
  "Nova Iguaçu",
  "Mesquita",
  "Belford Roxo",
  "Queimados",
  "Comendador Soares",
  "Nilópolis",
  "Posse",
  "Duque de Caxias",
  "Campos Elíseos",
  "Xerém",
  "Imbariê",
  "Japerí",
  "Vilar dos Teles",
  "Magé",
  "Piabetá",
  "Guapimirim",
  "Tanguá",
  "Itaboraí",
  "São Gonçalo",
  "Neves",
  "Alcantara",
  "Rio do Ouro",
  "Niterói",
  "Icaraí",
  "Fonseca",
  "Jurujuba",
  "Itaipú",
  "Maricá",
  "Paty de Alferes",
  "Barra do Piraí",
  "Resende",
  "Barra Mansa",
  "Valença",
  "Rio das Flores",
  "Volta Redonda",
  "Piraí",
  "Vassouras",
  "Miguel Pereira",
  "Mendes",
  "Paulo de Frontin",
  "Itatiaia",
  "Porto Real",
  "Pinheiral",
  "São José do Rio Preto",
  "Petrópolis",
  "Itaipava",
  "Paraíba do Sul",
  "Três Rios",
  "Sapucaia",
  "Teresópolis",
  "Sumidouro",
  "Carmo",
  "Araruama",
  "Rio Bonito",
  "Silva Jardim",
  "Casimiro de Abreu",
  "Conceição de Macabú",
  "Macaé",
  "Saquarema",
  "São Pedro da Aldeia",
  "Cabo Frio",
  "Búzios",
  "Rio das Ostras",
  "Iguaba",
  "Quissamã",
  "Arraial do Cabo",
  "Campos",
  "Itaocara",
  "Santo Antonio de Pádua",
  "Miracema",
  "Lajes de Muriaré",
  "Porciúncula",
  "Natividade",
  "São Fidelis",
  "Cambucí",
  "Itaperuna",
  "Bom Jesus Itabapoana",
  "São João da Barra",
  "Guarus",
  "São Francisco de Itabapoana",
  "Italva",
  "Nova Friburgo",
  "Duas Barras",
  "Cantagalo",
  "Cordeiro",
  "São Sebastião do Alto",
  "Santa Maria Madalena",
  "Trajano de Morais",
  "Bom Jardim",
  "Cachoeira de Macacú",
  "Mangaratiba",
  "Angra dos Reis",
  "Parati",
  "Rio Claro")

##Clear deadkeys
local <- iconv(local, from = 'latin1', to = 'ASCII//TRANSLIT')
## create a new address vector adding string "Rio de Janeiro" . This is important, cause in Brazil there are many places with same name 
address <- paste("Rio de Janeiro ", local, sep = ",")
##call geocode function where source is google and output is more detailed
geo <- geocode(address, source = 'google', output = 'more')
##create a geo_new dataframe using local and geo vectors
geo_new <- data.frame(local, geo)


geo





